# Generated by Django 4.1.7 on 2023-08-08 21:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AisthDasi',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('thesh', models.CharField(blank=True, db_column='THESH', max_length=200, null=True)),
            ],
            options={
                'db_table': 'aisth_dasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtipesViomSygk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('toponymio', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'atipes_viom_sygk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorineBiotopes',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('site_code', models.CharField(blank=True, max_length=254, null=True)),
                ('site_name_field', models.CharField(blank=True, db_column='site_name_', max_length=254, null=True)),
                ('threat_tex', models.CharField(blank=True, max_length=254, null=True)),
                ('measures_t', models.CharField(blank=True, max_length=254, null=True)),
                ('measures_n', models.CharField(blank=True, max_length=254, null=True)),
                ('quality', models.CharField(blank=True, max_length=254, null=True)),
                ('vulnerabil', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'corine_biotopes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiethneisSinthikes',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('kode', models.CharField(blank=True, max_length=254, null=True)),
                ('area', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diethneis_sinthikes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('objectid', models.IntegerField(blank=True, db_column='OBJECTID', null=True)),
                ('lektiko', models.CharField(blank=True, db_column='LEKTIKO', max_length=200, null=True)),
            ],
            options={
                'db_table': 'dimEn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimoiKal',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=200, null=True)),
            ],
            options={
                'db_table': 'dimoi_kal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElegxKinPer',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'elegx_kin_per',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EthnDrymoi',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('category', models.CharField(blank=True, db_column='CATEGORY', max_length=200, null=True)),
                ('thesh', models.CharField(blank=True, db_column='THESH', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ethn_drymoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EthnParka',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=200, null=True)),
                ('zone', models.CharField(blank=True, db_column='ZONE', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ethn_parka',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GpsAttikis',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('xriseis', models.CharField(blank=True, db_column='XRISEIS', max_length=200, null=True)),
                ('shetika', models.CharField(blank=True, db_column='SHETIKA', max_length=200, null=True)),
            ],
            options={
                'db_table': 'gps_attikis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KatAgriasZois',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('kode', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('fek', models.CharField(blank=True, max_length=254, null=True)),
                ('area', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kat_agrias_zois',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LekanesApor',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'lekanes_apor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoipaTopia',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('site_code', models.CharField(blank=True, max_length=254, null=True)),
                ('site_name_field', models.CharField(blank=True, db_column='site_name_', max_length=254, null=True)),
            ],
            options={
                'db_table': 'loipa_topia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Natura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('objectid', models.FloatField(blank=True, db_column='OBJECTID', null=True)),
                ('name_latin', models.CharField(blank=True, db_column='NAME_LATIN', max_length=200, null=True)),
            ],
            options={
                'db_table': 'natura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nomoi',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('name_gr', models.CharField(blank=True, db_column='NAME_GR', max_length=200, null=True)),
                ('edra', models.CharField(blank=True, db_column='EDRA', max_length=200, null=True)),
            ],
            options={
                'db_table': 'nomoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParagogDrast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('xrhseis', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'paragog_drast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perifereies',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('per', models.CharField(blank=True, db_column='PER', max_length=200, null=True)),
            ],
            options={
                'db_table': 'perifereies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Railway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('objectid', models.FloatField(blank=True, db_column='OBJECTID', null=True)),
                ('shape_leng', models.FloatField(blank=True, db_column='Shape_Leng', null=True)),
            ],
            options={
                'db_table': 'railway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestBiotopes',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('site_code', models.CharField(blank=True, max_length=254, null=True)),
                ('site_name_field', models.CharField(blank=True, db_column='site_name_', max_length=254, null=True)),
            ],
            options={
                'db_table': 'rest_biotopes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tifk',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('site_code', models.CharField(blank=True, max_length=254, null=True)),
                ('site_name_field', models.CharField(blank=True, db_column='site_name_', max_length=254, null=True)),
            ],
            options={
                'db_table': 'tifk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='XriseisAktesAttiki',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('xriseis', models.CharField(blank=True, db_column='XRISEIS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'xriseis_aktes_attiki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZeaAttikiOdos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=3, null=True, srid=4326)),
                ('shape_leng', models.FloatField(blank=True, db_column='Shape_Leng', null=True)),
                ('shape_area', models.FloatField(blank=True, db_column='Shape_Area', null=True)),
            ],
            options={
                'db_table': 'zea_attiki_odos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZeaElaiona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=3, null=True, srid=4326)),
                ('xrhseis', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'zea_elaiona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZoeMesogeion',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('xriseis', models.CharField(blank=True, db_column='XRISEIS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'zoe_mesogeion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonesProstasiasAigaleo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('zones', models.CharField(blank=True, db_column='ZONES', max_length=200, null=True)),
            ],
            options={
                'db_table': 'zones_prostasias_aigaleo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZoniParnithas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('id_0', models.IntegerField(blank=True, db_column='ID', null=True)),
                ('ypozones', models.CharField(blank=True, db_column='YPOZONES', max_length=200, null=True)),
            ],
            options={
                'db_table': 'zoni_parnithas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZoniProstasiasLauriou',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'zoni_prostasias_lauriou',
                'managed': False,
            },
        ),
    ]
