# Generated by Django 4.1.7 on 2023-08-29 13:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimenTot',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('dimen', models.CharField(blank=True, max_length=254, null=True)),
                ('dimos', models.CharField(blank=True, max_length=254, null=True)),
                ('peren', models.CharField(blank=True, max_length=254, null=True)),
                ('perifereia', models.CharField(blank=True, max_length=254, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('urban', models.FloatField(blank=True, null=True)),
                ('pop', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'dimen_tot',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AisthDasi',
        ),
        migrations.DeleteModel(
            name='AtipesViomSygk',
        ),
        migrations.DeleteModel(
            name='CorineBiotopes',
        ),
        migrations.DeleteModel(
            name='DiethneisSinthikes',
        ),
        migrations.DeleteModel(
            name='Dimen',
        ),
        migrations.DeleteModel(
            name='DimoiKal',
        ),
        migrations.DeleteModel(
            name='ElegxKinPer',
        ),
        migrations.DeleteModel(
            name='EthnDrymoi',
        ),
        migrations.DeleteModel(
            name='EthnParka',
        ),
        migrations.DeleteModel(
            name='GpsAttikis',
        ),
        migrations.DeleteModel(
            name='KatAgriasZois',
        ),
        migrations.DeleteModel(
            name='LekanesApor',
        ),
        migrations.DeleteModel(
            name='LoipaTopia',
        ),
        migrations.DeleteModel(
            name='Natura',
        ),
        migrations.DeleteModel(
            name='Nomoi',
        ),
        migrations.DeleteModel(
            name='ParagogDrast',
        ),
        migrations.DeleteModel(
            name='Perifereies',
        ),
        migrations.DeleteModel(
            name='Railway',
        ),
        migrations.DeleteModel(
            name='RestBiotopes',
        ),
        migrations.DeleteModel(
            name='Tifk',
        ),
        migrations.DeleteModel(
            name='XriseisAktesAttiki',
        ),
        migrations.DeleteModel(
            name='ZeaAttikiOdos',
        ),
        migrations.DeleteModel(
            name='ZeaElaiona',
        ),
        migrations.DeleteModel(
            name='ZoeMesogeion',
        ),
        migrations.DeleteModel(
            name='ZonesProstasiasAigaleo',
        ),
        migrations.DeleteModel(
            name='ZoniParnithas',
        ),
        migrations.DeleteModel(
            name='ZoniProstasiasLauriou',
        ),
    ]
