version: "3"
services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 7000:8000
    volumes:
      - ./backend:/app

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 1000:80
    volumes:
      - ./frontend:/app
    depends_on:
      - django
